### ISSUE TITLE
Drop README and README.TXT in favour of README.md

### ISSUE THREAD

**Issue by zstyblik** [entropy1337/infernal-twin#24]
Hi,

up for consideration/thought is to drop README and README.TXT in favour of README.md which is a text file as well, although with markup language. The reason is triplication of information and keeping these files in sync which I believe is going to be the last thing they're going to be in.
There is a price to pay, though. As I've mentioned in https://github.com/entropy1337/infernal-twin/issues/5, escaped characters, `\*`, can be confusing. I'm not sure(meaning I haven't looked for it) if there is a CLI tool that would strip markup and produced plain TXT without it.

My $0.02USD.

**Comment by entropy1337** [comment]
it is done. thanks,
