### ISSUE TITLE
question about interface checks

### ISSUE THREAD

**Issue by zstyblik** [entropy1337/infernal-twin#26]
Hello,

I have a question about the following code which can be seen at multiple places:

```Python
[...]
proc = subprocess.Popen(["ifconfig", ""], stdout=subprocess.PIPE, shell=True)
(out2, err) = proc.communicate()
[...]
if monitoring_interface in out2:
  # Do stuff
  ssid = str(self.ask(message = 'Enter the SSID')).strip()
  MAC = str(self.ask(message = 'Enter the MAC')).strip()
  [...]
else:
  wx.MessageBox('make sure you have mon0 interface', 'Warning/Error', wx.ICON_ERROR | wx.ICON_INFORMATION)
```

What's exactly the purpose of these checks? `ifconfig` is called and then, say, `wlan0` is searched in its output. I believe we can get this information elsewhere, resp. we are already getting it from elsewhere.

Also, I found a bug here, because we won't get `mon0` interface, but whatever interface comes first. :)

Thank you,
Z.

**Comment by entropy1337** [comment]
Hello Zdenek, I was here trying to list the interfaces and see if monitoring interface is out. if Monitoring interface there, then proceed with asking the user to enter the MAC and SSID of the target to deauthenticate and execute the command. Honestly, I got to admit, I might have come up with something better. That function had to check only monitoring interface only not other interfaces. I will double check the attack again.

**Comment by zstyblik** [comment]
I see. Looking at the code in `wless_command.py`, resp. `get_monitoring_interfaces()`, I believe these calls and ifconfig checks can be dropped. Its output shouldn't be different from `/proc/net/dev`, at least so I believe.

**Comment by zstyblik** [comment]
I believe this have been fixed as part of https://github.com/entropy1337/infernal-twin/pull/28.
