### ISSUE TITLE
WPA crack/any crack should use BSSID instead of ESSID

### ISSUE THREAD

**Issue by zstyblik** [entropy1337/infernal-twin#31]
WPA crack or any cracking should use BSSID instead of ESSID. The reason is, there can be N APs with the same ESSID. Also, there happen to be APs with no ESSID at all.

This is an easy thing to fix.

**Comment by entropy1337** [comment]
Great!
I will fix it tonight.
Thanks for comments.

**Comment by zstyblik** [comment]
Give me a minute. I have staged changes for WPA crack. These changes are reason why I thought about this issue, but they don't address it.

**Comment by entropy1337** [comment]
Sure thing.
Thanks

**Comment by zstyblik** [comment]
Basically, it's enough to parse out BSSID information instead of ESSID, and then change `--essid` to `--bssid`(please, check for the correct flag), and that's about it. Oh, and replace ':' for '_' or whatever in the name of capture file.

**Comment by zstyblik** [comment]
Hm, it seems I've either referenced wrong issue or it must be referenced in the body of the commit message. Anyway, this should have been fixed by https://github.com/entropy1337/infernal-twin/pull/37
