### ISSUE TITLE
It should be possible to dedicate/choose interfaces

### ISSUE THREAD

**Issue by zstyblik** [entropy1337/infernal-twin#35]
Hello,

I believe it'd be great if you could either choose roles for devices, or dedicate device to some specific task, or even "blacklist" device(= don't touch this device). I mean, what if you want to use `wlan1` for wireless scan? What if you want to "provide" free Internet over wlan interface instead of eth0?

It might be nice to have feature.

**Comment by entropy1337** [comment]
Hi, 
That is on the task list. 
This got to be implemented soon. 
I was thinking we should correct current issues and make it more stable. 
That is a good point. I initially thought of using via VMware only, but even in that case this kind of finer control of the tool is a good way to do.

**Comment by zstyblik** [comment]
Sure, it doesn't have to be fixed right now. But I'd forget about it otherwise. ;) And perhaps somebody else will pick up this task. You never know :)

**Comment by entropy1337** [comment]
thank you for mentioning here. 
I will put that under task list and we can come back to it at a later time. 
Hopefully more people start joining us to improve the tool. 
thanks,

**Comment by entropy1337** [comment]
This feature is implemented now. 
thanks
