### ISSUE TITLE
Not able to connect to db

### ISSUE THREAD

**Issue by sherubinsky** [entropy1337/infernal-twin#42]
Hi ,i have follow the step describe here but is not working for me !

i have delete the dbconnect.conf 

then i enter a user and pass and i have this for result 

Creds are not correct
Traceback (most recent call last):
  File "InfernalWireless.py", line 20, in <module>
    cxn = MySQLdb.connect('localhost',str(dbfile[0]).replace('\n',''),str(dbfile[1]).replace('\n',''))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root2'@'localhost' (using password: YES)")

i have try this
/etc/init.d/mysql start

i have try this also

Run the following command from your mysql console.

mysql>use mysql;

mysql>CREATE USER 'root2'@'localhost' IDENTIFIED BY 'enter the new password here';

mysql>GRANT ALL PRIVILEGES ON \*.\* TO 'root2'@'localhost' WITH GRANT OPTION;

no more success this way

i specify that i use  Kali GNU/Linux 2.0 (sana) 32-bit -gnome 3.14.1

what i do wrong? any help is very appreciated.

**Comment by sherubinsky** [comment]
Correction now i have redone this step 

mysql>use mysql;

mysql>CREATE USER 'root2'@'localhost' IDENTIFIED BY 'enter the new password here';

mysql>GRANT ALL PRIVILEGES ON *.* TO 'root2'@'localhost' WITH GRANT OPTION;

and now everything look like it's working ! I just don't know why is never working the other time.

**Comment by entropy1337** [comment]
Hello Sherubinsky, I am glad that it is working.
