### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [entropy1337/infernal-twin#5]
Hi my OS is Kali Linux Linux kali 3.18.0-kali3-686-pae #1 SMP Debian 3.18.6-1~kali2
I get this error message 
root@kali:~/infernal-twin# sudo ./Makefile
./Makefile: line 1: AC_ROOT: command not found
./Makefile: line 2: DOCFILES: command not found
./Makefile: line 3: AC_ROOT: command not found
./Makefile: line 3: include: command not found
./Makefile: line 5: default:: command not found
./Makefile: line 7: all:: command not found
./Makefile: line 8: @echo: command not found
./Makefile: line 10: install:: command not found
./Makefile: line 11: prefix: command not found
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/graphviz
copying graphviz/lib_Airgraphviz.py -> build/lib.linux-i686-2.7/graphviz
copying graphviz/__init__.py -> build/lib.linux-i686-2.7/graphviz
copying graphviz/libOuiParse.py -> build/lib.linux-i686-2.7/graphviz
copying graphviz/libDumpParse.py -> build/lib.linux-i686-2.7/graphviz
running build_scripts
creating build/scripts-2.7
copying dump-join -> build/scripts-2.7
error: airgraph-ng: Is a directory
./Makefile: line 13: doc:: command not found
./Makefile: line 14: MAKE: command not found
./Makefile: line 14: -C: command not found
./Makefile: line 15: prefix: command not found
./Makefile: line 15: docdir: command not found
install: missing file operand
Try `install --help' for more information.
./Makefile: line 16: prefix: command not found
./Makefile: line 17: DOCFILES: command not found
./Makefile: line 17: DESTDIR: command not found
./Makefile: line 17: docdir: command not found
install: missing file operand
Try `install --help' for more information.
./Makefile: line 19: uninstall:: command not found
./Makefile: line 20: MAKE: command not found
./Makefile: line 20: @: command not found
./Makefile: line 20: -C: command not found
cat: files.txt: No such file or directory
./Makefile: line 24: clean:: command not found
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
running clean
./Makefile: line 28: distclean:: command not found

when i type 
./setup.py i got this 
root@kali:~/infernal-twin# ./setup.py
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

how to start infernal-twin
Thank you !

**Comment by entropy1337** [comment]
could you try to run the following command from the folder where downloaded the tool ? 
python InfernalWireless.py

**Comment by entropy1337** [comment]
could you look at the video https://www.youtube.com/watch?v=0zVXMfOFWv0

**Comment by wermaxta** [comment]
hi i type  python InfernalWireless.py  i got this how to fix it 
Thank you :)

root@kali:~/Desktop/infernal-twin# python InfernalWireless.py 
[....] Starting web server: apache2apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1 for ServerName
. ok 
[ ok ] Starting MySQL database server: mysqld already running.
Creating DB config file
dbconnect.conf doesn't exists or creds are incorrect
*************** creating DB config file ************
Enter the DB username: root
Enter the password: 
trying to connect
username root

password 

Creds are not correct
Traceback (most recent call last):
  File "InfernalWireless.py", line 30, in <module>
    cxn = MySQLdb.connect(db='InfernalWireless')
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by entropy1337** [comment]
Hello dude,
Did you manage to fix the issue ?
You seem to have incorrect  credentials. If you still did not manage to
fix, let me know .

Thanks

**Comment by FreelancePentester** [comment]
the same error as @wermaxta although I had correct credentials on Kali linux 2.0

**Comment by entropy1337** [comment]
hello folks, 
eventually there was a hick up. There seem to be a user 'root' or what ever user you had but might have had different privileges or creds. well, anyway the fix is you need to create new account and perform the followings: 
1. Delete dbconnect.conf file
2.run the following command from your mysql console. 
mysql>use mysql;
mysql> CREATE USER 'root2'@'localhost' IDENTIFIED BY 'enter the new password here';
mysql> GRANT ALL PRIVILEGES ON *.* TO 'root2'@'localhost' WITH GRANT OPTION;

3. Try to run the tool again.

**Comment by FreelancePentester** [comment]
@entropy1337 not work... :(

**Comment by entropy1337** [comment]
Did you try to set up the database with another user?
If you are still facing issue with dB error, I will write the code which
would set up the dB . Please let me know what's the issue now? U can email
me 3ntr0py1337@gmail.com

**Comment by entropy1337** [comment]
it is fixed

**Comment by maximebodereau** [comment]
Hi, I had an error :
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\*.\* TO 'root2'@'localhost' WITH GRANT OPTION' at line 1

Any clue ?

**Comment by zstyblik** [comment]
I had this one too. I believe you must escape `*` like `\*.\*`, but let me check.

**Comment by entropy1337** [comment]
Hello Maxim,
Could you please send me the screenshot?
By the way, I have just uploaded the latest version. Could you try the
latest version ?

**Comment by zstyblik** [comment]
Actually, I had it mixed up. https://github.com/entropy1337/infernal-twin/blob/master/README.md says:

> GRANT ALL PRIVILEGES ON \*.\* TO 'root2'@'localhost' WITH GRANT OPTION;

whereas in a fact it is:

> GRANT ALL PRIVILEGES ON *.* TO 'root2'@'localhost' WITH GRANT OPTION;

and it should work, resp. at least that's how it works with mysql 5.5.44.
