### ISSUE TITLE
can't run "python InfernalWireless.py"

### ISSUE THREAD

**Issue by itachi66** [entropy1337/infernal-twin#51]
i get this :
Traceback (most recent call last):
  File "InfernalWireless.py", line 82, in <module>
    db_setup.create_db(cur, db_setup.INFERNAL_DB, username, password)
  File "/root/infernal-twin/Modules/db_setup.py", line 52, in create_db
    dbcurr.execute(grant_all)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table 'mysql.user' doesn't exist")

**Comment by ndrix** [comment]
If you do the following:
`$ mysqlshow -u root -p mysql`

What output do you see?

**Comment by itachi66** [comment]
Enter password:

**Comment by ndrix** [comment]
:-| I mean after you put your mysql password.

**Comment by itachi66** [comment]
i don't know the password but for every password i enter i get this :
mysqlshow: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by ndrix** [comment]
It means your mysql server isn't running, make sure it's running.  Probably `# service mysql start`

**Comment by itachi66** [comment]
same output after starting service

**Comment by entropy1337** [comment]
Hello Itachi, 
On the folder you will see dbconnect.conf 
Try to put your MySQL username and password manually. 
With what privileges are you running the tool ?

Kind regards,
Khalilov

**Comment by itachi66** [comment]
dbconnect.conf has only one word in it "root" and i'm running the tool with root privileges.
it's my first experience with MySQL so i don't know what to put there in dbconnect.conf

**Comment by entropy1337** [comment]
Under root put your password and run it again. 
For example your file should look like this

root
toor 

Kind regards,
Khalilov

**Comment by itachi66** [comment]
same output:
`# python InfernalWireless.py 
Traceback (most recent call last):
  File "InfernalWireless.py", line 80, in <module>
    cxn = MySQLdb.connect('localhost', username, password)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")`

**Comment by itachi66** [comment]
i managed to make it work by this :
`apt-get purge mysql*
apt-get install mysql-server
apt-get install python-mysqldb`
and editing dbconnect.conf with my username and password.
thanks all for helping me.
