### ISSUE TITLE
Error starting Fake WPA2 AP

### ISSUE THREAD

**Issue by Adz000** [entropy1337/infernal-twin#52]
When i try and start a fake WPA2 AP i get this error in systemctl status networking.service???

I can start an open Fake AP no problem.  Any ideas?

● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-03-23 00:16:20 EDT; 32min ago
     Docs: man:interfaces(5)
 Main PID: 7246 (code=exited, status=1/FAILURE)

Mar 23 00:16:20 kali systemd[1]: Starting Raise network interfaces...
Mar 23 00:16:20 kali ifup[7246]: Cannot find device "br0"
Mar 23 00:16:20 kali ifup[7246]: Failed to bring up br0.
Mar 23 00:16:20 kali systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 00:16:20 kali systemd[1]: Failed to start Raise network interfaces.
Mar 23 00:16:20 kali systemd[1]: networking.service: Unit entered failed state.
Mar 23 00:16:20 kali systemd[1]: networking.service: Failed with result 'exit-code'.

**Comment by Adz000** [comment]
Sorted.  Didn't check kill the processes first

**Comment by entropy1337** [comment]
Hi,
I am glad it is working now

Kind regards,
Khalilov
