### ISSUE TITLE
Can't connect to database..

### ISSUE THREAD

**Issue by theoneandonly-vector** [entropy1337/infernal-twin#6]
I gave my credentials correctly to the program, as it asked.. They are also correctly written in dbconnect.conf.
But it tries to connect without a Pasword..
I could normally access my mysql-server using mysql -p
output:
[ ok ] Starting apache2 (via systemctl): apache2.service.
[ ok ] Starting mysql (via systemctl): mysql.service.
DB Config files is found
Traceback (most recent call last):
  File "./InfernalWireless.py", line 30, in <module>
    cxn = MySQLdb.connect(db='InfernalWireless')
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by entropy1337** [comment]
HI,  try to delete the configuration file which contains your password and
username. Rerun the program, and enter new username and password.
The credentials could have been used with other applications.
Please let me know the result for this. Thank you

**Comment by theoneandonly-vector** [comment]
no change.
Am 18.09.2015 22:09 schrieb "KHalilov M" <notifications@github.com>:

**Comment by entropy1337** [comment]
You are trying to connect with the username root. Delete the configuration
file and when it asks to create a new user, enter new user account like
root2 and a new password. Confirm that configuration file has got 2 lines
which shows those new creds.
Thanks

**Comment by theoneandonly-vector** [comment]
that wouldn't work.. access denied for user root2 @ localhost using
password=yes
Am 18.09.2015 22:28 schrieb "KHalilov M" <notifications@github.com>:

**Comment by entropy1337** [comment]
the issue is fixed

**Comment by rajunromen** [comment]
How to run this program? can run it using proxy server like xampp because it has a built-in mysql. Please teach me on how to run it.

**Comment by entropy1337** [comment]
Give me few hours and I will upload the fix. Thank you
